//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontmiddleend.Models
{
    using System;
    
    public partial class CustomerCity
    {
        public string City { get; set; }
        public int Antal { get; set; }
    }
}
