//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontmiddleend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<TimeSlots> TimeSlots { get; set; }
    
        public virtual int AvailableSlots(Nullable<System.DateTime> dT)
        {
            var dTParameter = dT.HasValue ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AvailableSlots", dTParameter);
        }
    
        public virtual int CustomerCity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CustomerCity");
        }
    
        public virtual int CustomersPerDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CustomersPerDay");
        }
    
        public virtual ObjectResult<string> Procedure_Name()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Procedure_Name");
        }
    
        public virtual int sp_CLRNumberTwo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CLRNumberTwo");
        }
    
        public virtual int sp_getAge(string ageOrder)
        {
            var ageOrderParameter = ageOrder != null ?
                new ObjectParameter("ageOrder", ageOrder) :
                new ObjectParameter("ageOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getAge", ageOrderParameter);
        }
    
        public virtual int sp_GetNumberOfSlotsToCountHours(Nullable<System.DateTime> firstDT, Nullable<System.DateTime> secondDT)
        {
            var firstDTParameter = firstDT.HasValue ?
                new ObjectParameter("firstDT", firstDT) :
                new ObjectParameter("firstDT", typeof(System.DateTime));
    
            var secondDTParameter = secondDT.HasValue ?
                new ObjectParameter("secondDT", secondDT) :
                new ObjectParameter("secondDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetNumberOfSlotsToCountHours", firstDTParameter, secondDTParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TotalInOneRow()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TotalInOneRow");
        }
    
        public virtual int StoredProcedureOne(Nullable<System.DateTime> dT)
        {
            var dTParameter = dT.HasValue ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StoredProcedureOne", dTParameter);
        }
    
        public virtual int TotalCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TotalCustomers");
        }
    }
}
