//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontmiddleend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<TimeSlots> TimeSlots { get; set; }
    
        public virtual ObjectResult<AvailableSlots> AvailableSlots(Nullable<System.DateTime> dT)
        {
            var dTParameter = dT.HasValue ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AvailableSlots>("AvailableSlots", dTParameter);
        }
    
        public virtual ObjectResult<CustomerCity> CustomerCity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerCity>("CustomerCity");
        }
    
        public virtual ObjectResult<CustomersPerDay> CustomersPerDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomersPerDay>("CustomersPerDay");
        }
    
        public virtual ObjectResult<GetAge> sp_getAge(string ageOrder)
        {
            var ageOrderParameter = ageOrder != null ?
                new ObjectParameter("ageOrder", ageOrder) :
                new ObjectParameter("ageOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAge>("sp_getAge", ageOrderParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TotalInOneRow()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TotalInOneRow");
        }
    
        public virtual ObjectResult<TotalCustomers> TotalCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TotalCustomers>("TotalCustomers");
        }
    
        public virtual ObjectResult<GetNumberOfSlots> GetNumberOfSlots(Nullable<System.DateTime> firstDT, Nullable<System.DateTime> secondDT)
        {
            var firstDTParameter = firstDT.HasValue ?
                new ObjectParameter("firstDT", firstDT) :
                new ObjectParameter("firstDT", typeof(System.DateTime));
    
            var secondDTParameter = secondDT.HasValue ?
                new ObjectParameter("secondDT", secondDT) :
                new ObjectParameter("secondDT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNumberOfSlots>("GetNumberOfSlots", firstDTParameter, secondDTParameter);
        }
    
        public virtual ObjectResult<NumberOfBookingsPerCustomer> sp_NumberOfBookingsPerCustomer1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NumberOfBookingsPerCustomer>("sp_NumberOfBookingsPerCustomer1");
        }
    
        public virtual ObjectResult<AgeGroups> sp_getAgeGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AgeGroups>("sp_getAgeGroup");
        }
    }
}
